spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 266004587761-5n7ugbvdfaojbl67vbvdrluk69cfik0f.apps.googleusercontent.com
            client-secret: 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